import { Widgets } from "@mui/icons-material";

export const columns = [
  {
    field: "id",
    headerName: "ID",
    headerAlign: "center",
    align: "center",
    paddingLeft: 20,
    width: 100,
  },
  { field: "registrarId", headerName: "Registrar ID", width: 150 },
  {
    field: "name",
    headerName: "Name",
    cellClassName: "name-column--cell",
    width: 150,
  },
  {
    field: "age",
    headerName: "Age",
    type: "number",
    headerAlign: "left",
    align: "left",
    width: 50,
  },
  {
    field: "phone",
    headerName: "Phone Number",
    width: 150,
  },
  {
    field: "email",
    headerName: "Email",
    width: 200,
  },
  {
    field: "address",
    headerName: "Address",
    width: 200,
  },
  {
    field: "city",
    headerName: "City",
    width: 100,
  },
  {
    field: "zipCode",
    headerName: "Zip Code",
    width: 100,
  },
];

export const rows = [
  {
    id: 1,
    name: "Moahmed Rodriguez",
    email: "Mojamed@gmail.com",
    age: 35,
    phone: "972 59-786-7603",
    address: "Gaza - Omar Almokhtar",
    city: "Gaza",
    zipCode: "10001",
    registrarId: 123512,
  },
  {
    id: 2,
    name: "Ahmed",
    email: "ahmed@gmail.com",
    age: 42,
    phone: "+972 59-854-8459",
    address: "Gaza - Omar Almokhtar",
    city: "Gaza",
    zipCode: "13151",
    registrarId: 123512,
  },
  {
    id: 3,
    name: "Ali",
    email: "Ali@gmail.com",
    age: 45,
    phone: "+972 59-854-8958",
    address: "Gaza - Omar Almokhtar",
    city: "Gaza",
    zipCode: "87281",
    registrarId: 4132513,
  },
  {
    id: 4,
    name: "Abd",
    email: "abd@gmail.com",
    age: 16,
    phone: "(921)425-6742",
    address: "Gaza - Omar Almokhtar",
    city: "Gaza",
    zipCode: "15551",
    registrarId: 123512,
  },
  {
    id: 5,
    name: "Amal",
    email: "amal@gmail.com",
    age: 31,
    phone: "(421)445-1189",
    address: "Gaza - Omar Almokhtar",
    city: "Gaza",
    zipCode: "14215",
    registrarId: 123512,
  },
  {
    id: 6,
    name: "Noha",
    email: "noho@gmail.com",
    age: 78,
    phone: "(232)545-6483",
    address: "Gaza - Omar Almokhtar",
    city: "Gaza",
    zipCode: "10001",
    registrarId: 123512,
  },
  {
    id: 7,
    name: "Hala",
    email: "hala@gmail.com",
    age: 44,
    phone: "(543)124-0123",
    address: "Gaza - Omar Almokhtar",
    city: "Gaza",
    zipCode: "51523",
    registrarId: 123512,
  },
  {
    id: 8,
    name: "Shahed",
    email: "shahed@gmail.com",
    age: 36,
    phone: "(222)444-5555",
    address: "Gaza - Omar Almokhtar",
    city: "Gaza",
    zipCode: "44215",
    registrarId: 512315,
  },
  {
    id: 9,
    name: "Anas",
    email: "anas@gmail.com",
    age: 65,
    phone: "(444)555-6239",
    address: "Gaza - Omar Almokhtar",
    city: "Gaza",
    zipCode: "111234",
    registrarId: 928397,
  },
  {
    id: 10,
    name: "Suliman",
    email: "suliman@gmail.com",
    age: 42,
    phone: "(222)444-5555",
    address: "Gaza - Omar Almokhtar",
    city: "Gaza",
    zipCode: "44215",
    registrarId: 533215,
  },
  {
    id: 11,
    name: "Rateb",
    email: "rateb@gmail.com",
    age: 11,
    phone: "(444)555-6239",
    address: "Gaza - Omar Almokhtar",
    city: "Gaza",
    zipCode: "1234",
    registrarId: 92197,
  },
];
